name: Rush CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
    
    - name: Download Rush
      run: curl https://raw.githubusercontent.com/shreyashsaitwal/rush-cli/main/scripts/install/install.sh -fsSL | sh

    - name: Install Rush
      run: |
        chmod +x $HOME/.rush/bin/rush
        export PATH="$PATH:$HOME/.rush/bin"
    
    - name: Build extension
      run: rush build -r

    - name: Upload extension
      uses: actions/upload-artifact@v3.0.0
      with:
        path: './out/*.aix'
